import 'app-core/style/index.scss'
import './antd/date-picker/style/'
import './common.scss'

import '../components/form/input.scss'
import '../components/query-filter/query-filter.scss'
import './file-upload.scss'
import '../containers/common/page-common.scss'
import '../containers/app.scss'
import '../containers/1-todo-remind/todo-remind.scss'
import '../containers/2-customer/customer.scss'
import '../containers/3-project/project.scss'
import '../containers/4-contract/contract.scss'
import '../containers/5-report/report.scss'
import '../containers/6-recycle-bin/recycle-bin.scss'
import '../containers/7-account-manage/account-manage.scss'
